##### VSCODE / REST Client
# Create a .env file and set the corresponding variables
# See all $dotenv fields below

### Get access token use the writer
# @name login
POST https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username={{$dotenv AUTH_TEST_USERNAME}}
&password={{$dotenv AUTH_TEST_PASSWORD}}
&client_id=odh-mobility-datacollector-test
&client_secret={{$dotenv AUTH_TEST_CLIENT_SECRET}}

#@host=https://mobility.share.opendatahub.testingmachine.eu
#@host=http://localhost:8081
@host=http://localhost:8999
@authtoken = {{login.response.body.access_token}}

### Post some data to the writer

### Get all stationtypes from the writer
GET {{host}}/json/stations
Authorization: Bearer {{authtoken}}

