##### VSCODE / REST Client
# Create a .env file and set the corresponding variables
# See all $dotenv fields below

### Get access token for the writer (TEST)
# @name login
POST https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=odh-mobility-datacollector-development
&client_secret=7bd46f8f-c296-416d-a13d-dc81e68d0830

### Get access token for the writer (PROD)
# @name login
POST https://auth.opendatahub.bz.it/auth/realms/noi/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username={{$dotenv AUTH_PROD_USERNAME}}
&password={{$dotenv AUTH_PROD_PASSWORD}}
&client_id=odh-mobility-datacollector-test
&client_secret={{$dotenv AUTH_PROD_CLIENT_SECRET}}

#@host=https://mobility.share.opendatahub.bz.it
#@host=https://mobility.share.opendatahub.testingmachine.eu
@host=http://localhost:8999
@authtoken = {{login.response.body.access_token}}


### Get all stationtypes from the writer
GET {{host}}/json/stations?prn=dc-blabla&prv=1.0.2
Authorization: Bearer {{authtoken}}

### Get a single stationtype from the writer
GET {{host}}/json/stations/MeteoStation
Authorization: Bearer {{authtoken}}

### Get TrafficSensor stations (a22-elaborations)
GET {{host}}/json/stations/ON_DEMAND_VEHICLE
Authorization: Bearer {{authtoken}}

### Get TrafficSensor stations (a22-elaborations)
GET {{host}}/json/stations2/TrafficSensor
Authorization: Bearer {{authtoken}}

### Get a single stationtype from the writer
GET {{host}}/json/stations2/MeteoStation?origin=1111
Authorization: Bearer {{authtoken}}

### Get a single stationtype from the writer
GET {{host}}/json/stations/MeteoStation?origin=1111
Authorization: Bearer {{authtoken}}

### Get a single stationtype from the writer
GET {{host}}/json/provenance
Authorization: Bearer {{authtoken}}

### Get all datatypes from the writer
GET {{host}}/json/types
Authorization: Bearer {{authtoken}}

###
GET {{host}}/json/getDateOfLastRecord/TrafficSensor?stationId=A22:5416:2
Authorization: Bearer {{authtoken}}

### Post some data to the writer
POST {{host}}/json/provenance?prn=test&prv=11111
Content-Type: application/json
Authorization: Bearer {{authtoken}}

{
	"uuid": "abcTESTabc",
	"dataCollector": "TEST",
	"dataCollectorVersion": "1.1.1.1.1.1",
	"lineage": "xyz"
}

### Post a station
POST {{host}}/json/syncStations/EChargingStation34
?prn=test
&prv=11111
&syncState=true
&onlyActivation=true
Content-Type: application/json
Authorization: Bearer {{authtoken}}

[
	{
		"name": "PETER",
		"id": "PETER",
		"stationType": "EChargingStation",
		"origin": "abc"
	}
]

### Post stations states with "origin"
POST {{host}}/json/syncStationStates/EChargingStation/ALPERIA?prn=test&prv=11111
Content-Type: application/json
Authorization: Bearer {{authtoken}}

[
	"HER_00000059",
	"HER_00000003",
	"ASM_00000456",
	"A15_00000003"
]

### Post stations states without an "origin"
POST {{host}}/json/syncStationStates/EChargingStation?prn=test&prv=11111
Content-Type: application/json
Authorization: Bearer {{authtoken}}

[
	"HER_00000059",
	"HER_00000003",
	"ASM_00000456",
	"A15_00000003"
]

###
POST {{host}}/json/syncStationStates/EChargingStation/origin123
?prn=test
&prv=11111
&onlyActivation=true
Content-Type: application/json
Authorization: Bearer {{authtoken}}

[
	"HER_00000059",
	"HER_00000003",
	"ASM_00000456",
	"A15_00000003"
]


### Push Records
POST {{host}}/json/pushRecords/RWISstation
Content-Type: application/json
Authorization: Bearer {{authtoken}}

{
	"name": "(default)",

}

### Actuator / Healthcheck
GET {{host}}/actuator/health


###
GET {{host}}/error
