##### VSCODE / REST Client
# Create a .env file and set the corresponding variables
# See all $dotenv fields below

### Get access token use the writer
# @name login
POST https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username={{$dotenv AUTH_TEST_USERNAME}}
&password={{$dotenv AUTH_TEST_PASSWORD}}
&client_id=odh-mobility-datacollector-test
&client_secret={{$dotenv AUTH_TEST_CLIENT_SECRET}}

@host=https://mobility.share.opendatahub.testingmachine.eu
@host=http://localhost:8999
@authtoken = {{login.response.body.access_token}}


### Get all stationtypes from the writer
GET {{host}}/json/stations
Authorization: Bearer {{authtoken}}

### Get a single stationtype from the writer
GET {{host}}/json/stations2/MeteoStation
Authorization: Bearer {{authtoken}}

### Get a single stationtype from the writer
GET {{host}}/json/stations/MeteoStation
Authorization: Bearer {{authtoken}}

### Get TrafficSensor stations (a22-elaborations)
GET {{host}}/json/stations/ON_DEMAND_VEHICLE
Authorization: Bearer {{authtoken}}

### Get TrafficSensor stations (a22-elaborations)
GET {{host}}/json/stations2/TrafficSensor
Authorization: Bearer {{authtoken}}

### Get a single stationtype from the writer
GET {{host}}/json/stations2/MeteoStation?origin=1111
Authorization: Bearer {{authtoken}}

### Get a single stationtype from the writer
GET {{host}}/json/stations/MeteoStation?origin=1111
Authorization: Bearer {{authtoken}}

### Get a single stationtype from the writer
GET {{host}}/json/provenance
Authorization: Bearer {{authtoken}}

### Get all datatypes from the writer
GET {{host}}/json/types
Authorization: Bearer {{authtoken}}

###
GET {{host}}/json/getDateOfLastRecord/MeteoStation?stationId=T0009&period=900
Authorization: Bearer {{authtoken}}

### Post some data to the writer
POST {{host}}/json/provenance
Content-Type: application/json
Authorization: Bearer {{authtoken}}

{
	"uuid": "abcTESTabc",
	"dataCollector": "TEST",
	"dataCollectorVersion": "1.1.1.1.1.1",
	"lineage": "xyz"
}
