#
# writer - Data Writer for the Big Data Platform
#
# Copyright © 2018 IDM Südtirol - Alto Adige (info@idm-suedtirol.com)
# Copyright © 2019 NOI Techpark - Südtirol / Alto Adige (info@opendatahub.bz.it)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program (see LICENSES/GPL-3.0.txt). If not, see
# <http://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0
#

version: "3.4"
services:
  app:
    build:
      context: ./
      dockerfile: infrastructure/docker/Dockerfile
      target: base
    network_mode: bridge
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      MAVEN_CONFIG: /var/maven/.m2
      MAVEN_OPTS: -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8990
    command: mvn -Duser.home=/var/maven -Dmaven.tomcat.port=8999 spring-boot:run
    ports:
      - 8999:8999
      - 8990:8990
    volumes:
      - ~/.m2/:/var/maven/.m2
      - ./writer/:/code
    working_dir: /code
    tty: true

  # In case you had already one and changed some parameters here, docker-compose
  # might reuse the existing one and not update your password, DB or role... so
  # stop the containers and execute 'docker-compose rm -fv postgres' to get rid
  # of cached databases...
  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: bdp
      POSTGRES_USER: bdp
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/postgres/data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
