version: "3.4"
services:
  app:
    image: maven:3-jdk-8-alpine
    depends_on:
      - db
    env_file:
      - .env
    environment:
      MAVEN_CONFIG: /var/maven/.m2
      MAVEN_OPTS: -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8990
      SERVER_PORT: ${SERVER_PORT}
      SPRING_PROFILE: ${SPRING_PROFILE}
    command: >
      mvn
        -Dmaven.tomcat.port=${SERVER_PORT}
        -Duser.home=/var/maven
        -Dspring.profiles.active=${SPRING_PROFILE}
        clean spring-boot:run
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - 8990:8990
    volumes:
      - ~/.m2/:/var/maven/.m2
      - ./writer/:/code
    working_dir: /code
    tty: true

  # In case you had already one and changed some parameters here, docker-compose
  # might reuse the existing one and not update your password, DB or role... so
  # stop the containers and execute 'docker-compose rm -fv db' to get rid
  # of cached databases...
  db:
    image: postgis/postgis:12-3.2-alpine
    environment:
      POSTGRES_DB: bdp
      POSTGRES_USER: bdp
      POSTGRES_PASSWORD: password
    #volumes:
    #  - ./tmp/postgres/data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
