/**
 * BDP data - Data Access Layer for the Big Data Platform
 *
 * Copyright © 2018 IDM Südtirol - Alto Adige (info@idm-suedtirol.com)
 * Copyright © 2019 NOI Techpark - Südtirol / Alto Adige (info@opendatahub.bz.it)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program (see LICENSES/GPL-3.0.txt). If not, see
 * <http://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0
 */
package it.bz.odh.dal.authentication;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

import it.bz.odh.dal.DataType;
import it.bz.odh.dal.Station;

/**
 * <p>
 * Permissions define which role can access which data filtered by station, type<br/>
 * and period. Permissions is a generated database view by combining defined<br/>
 * rules with inheritance between roles. This entity is therefore readonly and<br/>
 * will not be generated by hibernate in the database
 * </p>
 *
 * @author Peter Moser
 *
 */
@Immutable
@Entity
@Table(name = "bdppermissions", indexes = { @Index(columnList = "station_id, type_id, period", name = "bdppermissions_stp_idx") })
public class BDPPermissions {

	@Id
	private Long uuid;

	@ManyToOne
	private BDPRole role;

	@ManyToOne
	private Station station;

	@ManyToOne
	private DataType type;

	private Integer period;

	public BDPRole getRole() {
		return role;
	}
	public void setRole(BDPRole role) {
		this.role = role;
	}
	public Station getStation() {
		return station;
	}
	public void setStation(Station station) {
		this.station = station;
	}
	public DataType getType() {
		return type;
	}
	public void setType(DataType type) {
		this.type = type;
	}
	public Integer getPeriod() {
		return period;
	}
	public void setPeriod(Integer period) {
		this.period = period;
	}
}
