# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    build:
      context: ../
      dockerfile: infrastructure/docker/Dockerfile
