# Default values for bdp-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/noi-techpark/bdp-core/bdp-core-app
  pullPolicy: Always
  tag: "unstable"

nameOverride: "bdp-core"
fullnameOverride: "bdp-core"
  
service:
  port: 80
  type: ClusterIP
  
health:
  delay: 10
    
ingress:
  enabled: false
  className: ""
  annotations: {}
  paths: 
    - path: "/*"
      pathType: ImplementationSpecific
  tls: []

env: {}
  
database: 
  servicebindName: 