name: CI dal

on:
  push:
    branches: [development, master]
    paths:
      - "dal/**"
      - "!README.md"
  pull_request:
    branches: [development, master]
    paths:
      - "dal/**"
      - "!README.md"


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Test with Maven
        run: cd dal && mvn -B -U clean compile test